/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nave_espacial.vista;

import javax.swing.JOptionPane;
import nave_espacial.modelo.Gasolinera;
import static nave_espacial.controlador.ControladorInicio.nave;

/**
 *
 * @author Lenovo
 */
public class ComprarGasolinaYsonda extends javax.swing.JDialog {
    /**
     * Creates new form ComprarGasolinaYsonda
     */
    public ComprarGasolinaYsonda(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        cantidadDeGasolinaAcomprar = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        cantidadDeSondasAcomprar = new javax.swing.JTextField();
        Comprar = new javax.swing.JButton();
        precioGasolinaIridio = new javax.swing.JLabel();
        precioGasolinaPaladio = new javax.swing.JLabel();
        precioGasolinaZero = new javax.swing.JLabel();
        precioGasolinaPlatino = new javax.swing.JLabel();
        precioSondaIridio = new javax.swing.JLabel();
        precioSondaPaladio = new javax.swing.JLabel();
        precioSondaZero = new javax.swing.JLabel();
        precioSondaPlatino = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Gasolinera");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Precio Gasolina Por 1000 Litro");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Precio Sonda");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel4.setText("Iridio:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel5.setText("Paladio:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel6.setText("Platino:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel7.setText("Zero:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel8.setText("Iridio:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel9.setText("Paladio:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel10.setText("Platino:");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel11.setText("Zero:");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("Cantidad De Litros A Comprar:");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("Cantidad De Sondas A Comprar:");

        Comprar.setText("Comprar");
        Comprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComprarActionPerformed(evt);
            }
        });

        precioGasolinaIridio.setText("precio");

        precioGasolinaPaladio.setText("precio");

        precioGasolinaZero.setText("precio");

        precioGasolinaPlatino.setText("precio");

        precioSondaIridio.setText("precio");

        precioSondaPaladio.setText("precio");

        precioSondaZero.setText("precio");

        precioSondaPlatino.setText("precio");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addComponent(jLabel7)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGap(2, 2, 2)
                                    .addComponent(jLabel6)))
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(precioGasolinaIridio, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(precioGasolinaPaladio, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(precioGasolinaZero, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(precioGasolinaPlatino, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cantidadDeGasolinaAcomprar, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(76, 76, 76))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(Comprar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel11)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(precioSondaIridio, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(precioSondaPaladio, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(precioSondaZero, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(precioSondaPlatino, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(cantidadDeSondasAcomprar, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(85, 85, 85))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel12))
                        .addGap(20, 20, 20))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 269, Short.MAX_VALUE)
                        .addComponent(Comprar)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(145, 145, 145)
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cantidadDeSondasAcomprar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(23, 23, 23)
                                        .addComponent(jLabel12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cantidadDeGasolinaAcomprar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(50, 50, 50))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel4)
                                                .addGap(40, 40, 40))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(precioGasolinaIridio, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(precioGasolinaPaladio, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel5))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(precioGasolinaPlatino, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel6))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(precioGasolinaZero, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel7))
                                                .addGap(21, 21, 21)))))
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel9))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(precioSondaIridio, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(precioSondaPaladio, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(precioSondaPlatino, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel10))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(precioSondaZero, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel11))))))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComprarActionPerformed
        Integer precioTotalgasolinaIridio = 0;
        Integer precioTotalgasolinaPaladio = 0;
        Integer precioTotalgasolinaPlatino = 0;
        Integer precioTotalgasolinaZero = 0;

        if (!cantidadDeGasolinaAcomprar.getText().equals("")) {
            precioTotalgasolinaIridio = (Integer.parseInt(cantidadDeGasolinaAcomprar.getText()) / 1000
                    * (Integer.parseInt(precioGasolinaIridio.getText())));
            precioTotalgasolinaPaladio = (Integer.parseInt(cantidadDeGasolinaAcomprar.getText()) / 1000
                    * +Integer.parseInt(precioGasolinaPaladio.getText()));
            precioTotalgasolinaPlatino = (Integer.parseInt(cantidadDeGasolinaAcomprar.getText()) / 1000
                    * +Integer.parseInt(precioGasolinaPlatino.getText()));
            precioTotalgasolinaZero = (Integer.parseInt(cantidadDeGasolinaAcomprar.getText()) / 1000
                    * +Integer.parseInt(precioGasolinaZero.getText()));

            for (String llave : nave.getCantidad_material_tienenave().keySet()) {
                if (llave.equals("iridio")) {
                    if (nave.getCantidad_material_tienenave().get(llave) >= precioTotalgasolinaIridio) {
                        if ((nave.getCantidad_conbustible() + Integer.parseInt(cantidadDeGasolinaAcomprar.getText())) <= 200000) {
                            
                            nave.getCantidad_material_tienenave().put(llave, nave.getCantidad_material_tienenave().get(llave) - precioTotalgasolinaIridio);
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "no tiene recursos para la  compra de gasolina");

                    }
                }

                if (llave.equals("paladio")) {
                    if (nave.getCantidad_material_tienenave().get(llave) >= precioTotalgasolinaPaladio) {
                        if ((nave.getCantidad_conbustible() + Integer.parseInt(cantidadDeGasolinaAcomprar.getText())) <= 200000) {
                            
                            nave.getCantidad_material_tienenave().put(llave, nave.getCantidad_material_tienenave().get(llave) - precioTotalgasolinaPaladio);
                       }
                    } else {
                        JOptionPane.showMessageDialog(null, "no tiene recursos para la  compra de gasolina");

                    }
                }

                if (llave.equals("platino")) {
                    if (nave.getCantidad_material_tienenave().get(llave) >= precioTotalgasolinaPlatino) {
                        if ((nave.getCantidad_conbustible() + Integer.parseInt(cantidadDeGasolinaAcomprar.getText())) <= 200000) {
                        nave.getCantidad_material_tienenave().put(llave, nave.getCantidad_material_tienenave().get(llave) - precioTotalgasolinaPlatino);
                       }
                    } else {
                        JOptionPane.showMessageDialog(null, "no tiene recursos para la  compra de gasolina");

                    }
                }
                
                if (llave.equals("zero")) {
                    if (nave.getCantidad_material_tienenave().get(llave) >= precioTotalgasolinaZero) {
                        if ((nave.getCantidad_conbustible() + Integer.parseInt(cantidadDeGasolinaAcomprar.getText())) <= 200000) {
                            
                            nave.getCantidad_material_tienenave().put(llave, nave.getCantidad_material_tienenave().get(llave) - precioTotalgasolinaZero);
                       }
                    } else {
                        JOptionPane.showMessageDialog(null, "no tiene recursos para la  compra de gasolina");

                    }
                }
                
            }
            nave.setCantidad_conbustible(nave.getCantidad_conbustible() + Integer.parseInt(cantidadDeGasolinaAcomprar.getText()));
            this.dispose();
        }
            
            //para comprar sondas 
            Integer precioTotalsondaIridio = 0;
            Integer precioTotalsondaPaladio = 0;
            Integer precioTotalsondaPlatino = 0;
            Integer precioTotalsondaZero = 0;

            if (!cantidadDeSondasAcomprar.getText().equals("")) {
                precioTotalsondaIridio = (Integer.parseInt(cantidadDeSondasAcomprar.getText())
                        * (Integer.parseInt(precioSondaIridio.getText())));
                precioTotalsondaPaladio = (Integer.parseInt(cantidadDeSondasAcomprar.getText())
                        * +Integer.parseInt(precioSondaPaladio.getText()));
                precioTotalsondaPlatino = (Integer.parseInt(cantidadDeSondasAcomprar.getText())
                        * +Integer.parseInt(precioSondaPlatino.getText()));
                precioTotalsondaZero = (Integer.parseInt(cantidadDeSondasAcomprar.getText())
                        * +Integer.parseInt(precioSondaZero.getText()));

            
            
            

            for (String llave : nave.getCantidad_material_tienenave().keySet()) {
                if (llave.equals("iridio")) {
                    if (nave.getCantidad_material_tienenave().get(llave) >= precioTotalsondaIridio) {
                        nave.getCantidad_material_tienenave().put(llave, nave.getCantidad_material_tienenave().get(llave) - precioTotalsondaIridio);
                    } else {
                        JOptionPane.showMessageDialog(null, "no tiene recursos para comprar sonda");
                    }
                }

                if (llave.equals("paladio")) {
                    if (nave.getCantidad_material_tienenave().get(llave) >= precioTotalsondaPaladio) {
                        nave.getCantidad_material_tienenave().put(llave, nave.getCantidad_material_tienenave().get(llave) - precioTotalsondaPaladio);
                    } else {
                        JOptionPane.showMessageDialog(null, "no tiene recursos para comprar sonda");
                    }
                }

                if (llave.equals("platino")) {
                    if (nave.getCantidad_material_tienenave().get(llave) >= precioTotalsondaPlatino) {
                        nave.getCantidad_material_tienenave().put(llave, nave.getCantidad_material_tienenave().get(llave) - precioTotalsondaPlatino);
                    } else {
                        JOptionPane.showMessageDialog(null, "no tiene recursos para comprar sonda");
                    }
                }

                if (llave.equals("zero")) {
                    if (nave.getCantidad_material_tienenave().get(llave) >= precioTotalsondaZero) {
                        nave.getCantidad_material_tienenave().put(llave, nave.getCantidad_material_tienenave().get(llave) - precioTotalsondaZero);
                    } else {
                        JOptionPane.showMessageDialog(null, "no tiene recursos para comprar sonda");
                    }
                }
            }
            nave.setNumero_sondas(nave.getNumero_sondas() + Integer.parseInt(cantidadDeSondasAcomprar.getText()));

            this.dispose();
        }
    }//GEN-LAST:event_ComprarActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ComprarGasolinaYsonda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ComprarGasolinaYsonda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ComprarGasolinaYsonda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ComprarGasolinaYsonda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ComprarGasolinaYsonda dialog = new ComprarGasolinaYsonda(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
 public void mostrarPrecios(Gasolinera gasolinera){
     this.precioGasolinaIridio.setText(String.valueOf(gasolinera.getPrecioGasolina().get("iridio")));
     this.precioGasolinaPaladio.setText(String.valueOf(gasolinera.getPrecioGasolina().get("paladio")));
     this.precioGasolinaPlatino.setText(String.valueOf(gasolinera.getPrecioGasolina().get("platino")));
     this.precioGasolinaZero.setText(String.valueOf(gasolinera.getPrecioGasolina().get("zero"))); 
     
     this.precioSondaIridio.setText(String.valueOf(gasolinera.getPrecioSonda().get("iridio")));
     this.precioSondaPaladio.setText(String.valueOf(gasolinera.getPrecioSonda().get("paladio")));
     this.precioSondaPlatino.setText(String.valueOf(gasolinera.getPrecioSonda().get("platino")));
     this.precioSondaZero.setText(String.valueOf(gasolinera.getPrecioSonda().get("zero")));   
 }
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Comprar;
    private javax.swing.JTextField cantidadDeGasolinaAcomprar;
    private javax.swing.JTextField cantidadDeSondasAcomprar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel precioGasolinaIridio;
    private javax.swing.JLabel precioGasolinaPaladio;
    private javax.swing.JLabel precioGasolinaPlatino;
    private javax.swing.JLabel precioGasolinaZero;
    private javax.swing.JLabel precioSondaIridio;
    private javax.swing.JLabel precioSondaPaladio;
    private javax.swing.JLabel precioSondaPlatino;
    private javax.swing.JLabel precioSondaZero;
    // End of variables declaration//GEN-END:variables
}
