/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nave_espacial.vista;

import javax.swing.JOptionPane;
import nave_espacial.modelo.Arma;
import nave_espacial.modelo.TiposArma;
import static nave_espacial.controlador.ControladorInicio.nave;
/**
 *
 * @author Lenovo
 */
public class ComprarArma extends javax.swing.JDialog {
 private TiposArma inventario= new TiposArma();
    /**
     * Creates new form ComprarArma
     */
    public ComprarArma(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        mostrarPrecios(inventario);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        imagenThanix = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        precioIridioThanix = new javax.swing.JLabel();
        precioPaladioThanix = new javax.swing.JLabel();
        precioPlatinoThanix = new javax.swing.JLabel();
        precioZeroThanix = new javax.swing.JLabel();
        imagenMultinucleo = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        precioIridioMultinucleo = new javax.swing.JLabel();
        precioPaladioMultinucleo = new javax.swing.JLabel();
        precioPlatinoMultinucleo = new javax.swing.JLabel();
        precioZeroMultinucleo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        precioIridioBlindaje = new javax.swing.JLabel();
        precioPaladioBlindaje = new javax.swing.JLabel();
        precioPlatinoBlindaje = new javax.swing.JLabel();
        precioZeroBlindaje = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        imagenBlindaje = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        precioZeroPropulsor = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        imagenPropulsor = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        precioIridioPropulsor = new javax.swing.JLabel();
        precioPaladioPropulsor = new javax.swing.JLabel();
        precioPlatinoPropulsor = new javax.swing.JLabel();
        precioZeroHielo = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        imagenHielo = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        imagenReactor = new javax.swing.JLabel();
        precioZeroInvisibilidad = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        imagenInvisibilidad = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        imagenEnergetica = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        precioIridioReactor = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        precioPaladioReactor = new javax.swing.JLabel();
        precioIridioInvisibilidad = new javax.swing.JLabel();
        precioPlatinoReactor = new javax.swing.JLabel();
        precioPaladioInvisibilidad = new javax.swing.JLabel();
        precioZeroReactor = new javax.swing.JLabel();
        precioPlatinoInvisibilidad = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        precioIridioEnergetica = new javax.swing.JLabel();
        precioPaladioEnergetica = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        precioIridioHielo = new javax.swing.JLabel();
        precioPlatinoEnergetica = new javax.swing.JLabel();
        precioPaladioHielo = new javax.swing.JLabel();
        precioZeroEnergetica = new javax.swing.JLabel();
        precioPlatinoHielo = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        comboBoxArmasComprar = new javax.swing.JComboBox<>();
        BotonComprarArma = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Comprar Arma");

        imagenThanix.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nave_espacial/vista/imagenes/armas/cañonThanix.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Iridio:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Paladio:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Platino:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Zero:");

        imagenMultinucleo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nave_espacial/vista/imagenes/armas/escudoMultinucleo.png"))); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Iridio:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Paladio:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Platino:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("Zero:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Cañon Thanix");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Escudo Multinucleo");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setText("Zero:");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Blindaje Naves Pesadas");

        imagenBlindaje.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nave_espacial/vista/imagenes/armas/blindajeNavesPesadas.png"))); // NOI18N
        imagenBlindaje.setText("arma");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setText("Iridio:");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel15.setText("Paladio:");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel16.setText("Platino:");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setText("Propulsor");

        imagenPropulsor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nave_espacial/vista/imagenes/armas/propulsor.png"))); // NOI18N

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel18.setText("Iridio:");

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel19.setText("Paladio:");

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel20.setText("Platino:");

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel21.setText("Zero:");

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel22.setText("Arma Hielo");

        imagenHielo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nave_espacial/vista/imagenes/armas/armaHielo.png"))); // NOI18N

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel23.setText("Iridio:");

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel24.setText("Paladio:");

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel25.setText("Platino:");

        imagenReactor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nave_espacial/vista/imagenes/armas/reactor.png"))); // NOI18N

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel26.setText("Invisibilidad");

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel27.setText("Iridio:");

        imagenInvisibilidad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nave_espacial/vista/imagenes/armas/invisibilidad.png"))); // NOI18N

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel28.setText("Paladio:");

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel29.setText("Iridio:");

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel30.setText("Platino:");

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel31.setText("Paladio:");

        imagenEnergetica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nave_espacial/vista/imagenes/armas/armaEnergetica.png"))); // NOI18N

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel32.setText("Zero:");

        jLabel33.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel33.setText("Platino:");

        jLabel34.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel34.setText("Iridio:");

        jLabel35.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel35.setText("Zero:");

        jLabel36.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel36.setText("Paladio:");

        jLabel37.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel37.setText("Platino:");

        jLabel38.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel38.setText("Arma Energetica");

        jLabel39.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel39.setText("Zero:");

        jLabel40.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel40.setText("Reactor");

        jLabel41.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel41.setText("Zero:");

        jLabel42.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel42.setText("Elegir arma a comprar :");

        comboBoxArmasComprar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cañon Thanix", "Escudo Multinucleo", "Blindaje Naves Pesadas", "Propulsor", "Arma Energetica (Luz)", "Reactor", "Arma De Hielo", "Invisibilidad" }));
        comboBoxArmasComprar.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboBoxArmasComprarItemStateChanged(evt);
            }
        });
        comboBoxArmasComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxArmasComprarActionPerformed(evt);
            }
        });

        BotonComprarArma.setText("Comprar");
        BotonComprarArma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonComprarArmaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(imagenMultinucleo, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(16, 16, 16)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(precioIridioMultinucleo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel7))
                                .addGap(49, 49, 49)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(precioPaladioMultinucleo, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(43, 43, 43)
                                        .addComponent(jLabel9)
                                        .addGap(12, 12, 12))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(precioPlatinoMultinucleo, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(29, 29, 29)
                                        .addComponent(jLabel10))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(precioZeroMultinucleo, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(imagenThanix, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(precioIridioThanix, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3))
                                .addGap(49, 49, 49)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(precioPaladioThanix, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(43, 43, 43)
                                        .addComponent(jLabel5)
                                        .addGap(12, 12, 12))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(precioPlatinoThanix, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(29, 29, 29)
                                        .addComponent(jLabel6))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(precioZeroThanix, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jLabel2)
                            .addComponent(jLabel11)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(imagenBlindaje, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(16, 16, 16)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(precioIridioBlindaje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel14))
                                .addGap(49, 49, 49)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15)
                                    .addComponent(precioPaladioBlindaje, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(43, 43, 43)
                                        .addComponent(jLabel16)
                                        .addGap(12, 12, 12))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(precioPlatinoBlindaje, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(29, 29, 29)
                                        .addComponent(jLabel12))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(precioZeroBlindaje, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jLabel13)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(imagenPropulsor, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(16, 16, 16)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(precioIridioPropulsor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel18))
                                .addGap(49, 49, 49)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel19)
                                    .addComponent(precioPaladioPropulsor, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(43, 43, 43)
                                        .addComponent(jLabel20)
                                        .addGap(12, 12, 12))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(precioPlatinoPropulsor, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(29, 29, 29)
                                        .addComponent(jLabel21))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(precioZeroPropulsor, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jLabel17))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(imagenReactor, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(16, 16, 16)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(precioIridioReactor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel27))
                                .addGap(49, 49, 49)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel28)
                                    .addComponent(precioPaladioReactor, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(43, 43, 43)
                                        .addComponent(jLabel30)
                                        .addGap(12, 12, 12))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(precioPlatinoReactor, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(29, 29, 29)
                                        .addComponent(jLabel32))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(precioZeroReactor, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(imagenEnergetica, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(precioIridioEnergetica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel34))
                                .addGap(49, 49, 49)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel36)
                                    .addComponent(precioPaladioEnergetica, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(43, 43, 43)
                                        .addComponent(jLabel37)
                                        .addGap(12, 12, 12))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(precioPlatinoEnergetica, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(29, 29, 29)
                                        .addComponent(jLabel39))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(precioZeroEnergetica, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jLabel38)
                            .addComponent(jLabel40)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(imagenHielo, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(16, 16, 16)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(precioIridioHielo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel23))
                                .addGap(49, 49, 49)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel24)
                                    .addComponent(precioPaladioHielo, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(43, 43, 43)
                                        .addComponent(jLabel25)
                                        .addGap(12, 12, 12))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(precioPlatinoHielo, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(29, 29, 29)
                                        .addComponent(jLabel41))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(precioZeroHielo, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jLabel22)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(imagenInvisibilidad, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(16, 16, 16)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(precioIridioInvisibilidad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel29))
                                .addGap(49, 49, 49)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel31)
                                    .addComponent(precioPaladioInvisibilidad, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(43, 43, 43)
                                        .addComponent(jLabel33)
                                        .addGap(12, 12, 12))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(precioPlatinoInvisibilidad, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(29, 29, 29)
                                        .addComponent(jLabel35))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(precioZeroInvisibilidad, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jLabel26)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BotonComprarArma)
                        .addGap(291, 291, 291)))
                .addGap(27, 27, 27))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(333, 333, 333)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel42)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(comboBoxArmasComprar, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(imagenThanix, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(precioIridioThanix, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(precioPaladioThanix, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(precioZeroThanix, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(precioPlatinoThanix, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(imagenMultinucleo, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(precioIridioMultinucleo, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(precioPaladioMultinucleo, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(precioZeroMultinucleo, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(precioPlatinoMultinucleo, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(imagenBlindaje, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(precioIridioBlindaje, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(precioPaladioBlindaje, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(precioZeroBlindaje, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(precioPlatinoBlindaje, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(imagenPropulsor, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(precioIridioPropulsor, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(precioPaladioPropulsor, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel20)
                                    .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(precioZeroPropulsor, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(precioPlatinoPropulsor, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel38)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(imagenEnergetica, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel34)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(precioIridioEnergetica, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel36)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(precioPaladioEnergetica, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel37)
                                    .addComponent(jLabel39, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(precioZeroEnergetica, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(precioPlatinoEnergetica, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel40)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(imagenReactor, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel27)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(precioIridioReactor, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel28)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(precioPaladioReactor, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel30)
                                    .addComponent(jLabel32, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(precioZeroReactor, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(precioPlatinoReactor, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(imagenHielo, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel23)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(precioIridioHielo, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel24)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(precioPaladioHielo, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel25)
                                    .addComponent(jLabel41, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(precioZeroHielo, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(precioPlatinoHielo, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel26)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(imagenInvisibilidad, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel29)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(precioIridioInvisibilidad, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel31)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(precioPaladioInvisibilidad, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel33)
                                    .addComponent(jLabel35, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(precioZeroInvisibilidad, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(precioPlatinoInvisibilidad, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel42)
                    .addComponent(comboBoxArmasComprar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonComprarArma))
                .addContainerGap(87, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonComprarArmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonComprarArmaActionPerformed
      Arma arma;
        Integer contador = 0;
        switch (comboBoxArmasComprar.getSelectedItem().toString()) {
            case "Cañon Cañon Thanix":
                arma = inventario.getCañonThanix();
                if (nave.getCantidad_material_tienenave() != null) {
                    contador = 0;
                    for (String llave : nave.getCantidad_material_tienenave().keySet()) {
                        if (nave.getCantidad_material_tienenave().get(llave) >= arma.getPrecio_del_arma().get(llave)) {
                            contador++;
                        }
                    }
                    if (contador == nave.getCantidad_material_tienenave().size()) {
                        for (String llave : nave.getCantidad_material_tienenave().keySet()) {
                            nave.getCantidad_material_tienenave().put(llave, nave.getCantidad_material_tienenave().get(llave) - arma.getPrecio_del_arma().get(llave));
                        }
                        nave.getArmas().add(arma);
                    } else {
                        JOptionPane.showMessageDialog(null,"no puede comprar arma");
                    }
                }
                break;

            case "Escudo Multinucleo":
                arma = inventario.getEscudoMultinucleo();
                if (nave.getCantidad_material_tienenave() != null) {
                    contador = 0;
                    for (String llave : nave.getCantidad_material_tienenave().keySet()) {
                        if (nave.getCantidad_material_tienenave().get(llave) >= arma.getPrecio_del_arma().get(llave)) {
                            contador++;
                        }
                    }
                    if (contador == nave.getCantidad_material_tienenave().size()) {
                        for (String llave : nave.getCantidad_material_tienenave().keySet()) {
                            nave.getCantidad_material_tienenave().put(llave, nave.getCantidad_material_tienenave().get(llave) - arma.getPrecio_del_arma().get(llave));
                        }
                        nave.getArmas().add(arma);
                    } else {
                        JOptionPane.showMessageDialog(null,"no puede comprar arma");
                    }
                }
                break;

            case "Blindaje naves Pesadas":
                arma = inventario.getBlindajeNavesPesadas();
                if (nave.getCantidad_material_tienenave() != null) {
                    contador = 0;
                    for (String llave : nave.getCantidad_material_tienenave().keySet()) {
                        if (nave.getCantidad_material_tienenave().get(llave) >= arma.getPrecio_del_arma().get(llave)) {
                            contador++;
                        }
                    }
                    if (contador == nave.getCantidad_material_tienenave().size()) {
                        for (String llave : nave.getCantidad_material_tienenave().keySet()) {
                            nave.getCantidad_material_tienenave().put(llave, nave.getCantidad_material_tienenave().get(llave) - arma.getPrecio_del_arma().get(llave));
                        }
                        nave.getArmas().add(arma);
                    } else {
                        JOptionPane.showMessageDialog(null,"no puede comprar arma");
                    }
                }
                break;

            case "Propulsor":
                arma = inventario.getPropulsor();
                if (nave.getCantidad_material_tienenave() != null) {
                    contador = 0;
                    for (String llave : nave.getCantidad_material_tienenave().keySet()) {
                        if (nave.getCantidad_material_tienenave().get(llave) >= arma.getPrecio_del_arma().get(llave)) {
                            contador++;
                        }
                    }
                    if (contador == nave.getCantidad_material_tienenave().size()) {
                        for (String llave : nave.getCantidad_material_tienenave().keySet()) {
                            nave.getCantidad_material_tienenave().put(llave, nave.getCantidad_material_tienenave().get(llave) - arma.getPrecio_del_arma().get(llave));
                        }
                        nave.getArmas().add(arma);
                    } else {
                        JOptionPane.showMessageDialog(null,"no puede comprar arma");
                    }
                }
                break;

            case " Arma Energetica (Luz)":
                arma = inventario.getArmaEnergeticaLuz();
                if (nave.getCantidad_material_tienenave() != null) {
                    contador = 0;
                    for (String llave : nave.getCantidad_material_tienenave().keySet()) {
                        if (nave.getCantidad_material_tienenave().get(llave) >= arma.getPrecio_del_arma().get(llave)) {
                            contador++;
                        }
                    }
                    if (contador == nave.getCantidad_material_tienenave().size()) {
                        for (String llave : nave.getCantidad_material_tienenave().keySet()) {
                            nave.getCantidad_material_tienenave().put(llave, nave.getCantidad_material_tienenave().get(llave) - arma.getPrecio_del_arma().get(llave));
                        }
                        nave.getArmas().add(arma);
                    } else {
                        JOptionPane.showMessageDialog(null,"no puede comprar arma");
                    }
                }
                break;

            case "Reactor":
                arma = inventario.getReactor();
                if (nave.getCantidad_material_tienenave() != null) {
                    contador = 0;
                    for (String llave : nave.getCantidad_material_tienenave().keySet()) {
                        if (nave.getCantidad_material_tienenave().get(llave) >= arma.getPrecio_del_arma().get(llave)) {
                            contador++;
                        }
                    }
                    if (contador == nave.getCantidad_material_tienenave().size()) {
                        for (String llave : nave.getCantidad_material_tienenave().keySet()) {
                            nave.getCantidad_material_tienenave().put(llave, nave.getCantidad_material_tienenave().get(llave) - arma.getPrecio_del_arma().get(llave));
                        }
                        nave.getArmas().add(arma);
                    } else {
                        JOptionPane.showMessageDialog(null,"no puede comprar arma");
                    }
                }
                break;

            case "Arma De Hielo":
                arma = inventario.getArmaHielo();
                if (nave.getCantidad_material_tienenave() != null) {
                    contador = 0;
                    for (String llave : nave.getCantidad_material_tienenave().keySet()) {
                        if (nave.getCantidad_material_tienenave().get(llave) >= arma.getPrecio_del_arma().get(llave)) {
                            contador++;
                        }
                    }
                    if (contador == nave.getCantidad_material_tienenave().size()) {
                        for (String llave : nave.getCantidad_material_tienenave().keySet()) {
                            nave.getCantidad_material_tienenave().put(llave, nave.getCantidad_material_tienenave().get(llave) - arma.getPrecio_del_arma().get(llave));
                        }
                        nave.getArmas().add(arma);
                    } else {
                        JOptionPane.showMessageDialog(null,"no puede comprar arma");
                    }
                }
                break;

            case "Invisibilidad":
                arma = inventario.getInvisibilidad();
                if (nave.getCantidad_material_tienenave() != null) {
                    contador = 0;
                    for (String llave : nave.getCantidad_material_tienenave().keySet()) {
                        if (nave.getCantidad_material_tienenave().get(llave) >= arma.getPrecio_del_arma().get(llave)) {
                            contador++;
                        }
                    }
                    if (contador == nave.getCantidad_material_tienenave().size()) {
                        for (String llave : nave.getCantidad_material_tienenave().keySet()) {
                            nave.getCantidad_material_tienenave().put(llave, nave.getCantidad_material_tienenave().get(llave) - arma.getPrecio_del_arma().get(llave));
                        }
                        nave.getArmas().add(arma);
                    } else {
                        JOptionPane.showMessageDialog(null,"no puede comprar arma");
                    }
                }
                break;
      }
        this.dispose();
    }//GEN-LAST:event_BotonComprarArmaActionPerformed

    private void comboBoxArmasComprarItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboBoxArmasComprarItemStateChanged

    }//GEN-LAST:event_comboBoxArmasComprarItemStateChanged

    private void comboBoxArmasComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxArmasComprarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxArmasComprarActionPerformed

    private void mostrarPrecios(TiposArma inventario){
        this.precioIridioThanix.setText(String.valueOf(inventario.getCañonThanix().getPrecio_del_arma().get("iridio")));
        this.precioPaladioThanix.setText(String.valueOf(inventario.getCañonThanix().getPrecio_del_arma().get("paladio")));
        this.precioPlatinoThanix.setText(String.valueOf(inventario.getCañonThanix().getPrecio_del_arma().get("platino")));
        this.precioZeroThanix.setText(String.valueOf(inventario.getCañonThanix().getPrecio_del_arma().get("zero")));
    
        this.precioIridioMultinucleo.setText(String.valueOf(inventario.getEscudoMultinucleo().getPrecio_del_arma().get("iridio")));
        this.precioPaladioMultinucleo.setText(String.valueOf(inventario.getEscudoMultinucleo().getPrecio_del_arma().get("paladio")));
        this.precioPlatinoMultinucleo.setText(String.valueOf(inventario.getEscudoMultinucleo().getPrecio_del_arma().get("platino")));
        this.precioZeroMultinucleo.setText(String.valueOf(inventario.getEscudoMultinucleo().getPrecio_del_arma().get("zero")));
    
        this.precioIridioBlindaje.setText(String.valueOf(inventario.getBlindajeNavesPesadas().getPrecio_del_arma().get("iridio")));
        this.precioPaladioBlindaje.setText(String.valueOf(inventario.getBlindajeNavesPesadas().getPrecio_del_arma().get("paladio")));
        this.precioPlatinoBlindaje.setText(String.valueOf(inventario.getBlindajeNavesPesadas().getPrecio_del_arma().get("platino")));
        this.precioZeroBlindaje.setText(String.valueOf(inventario.getBlindajeNavesPesadas().getPrecio_del_arma().get("zero")));
    
        this.precioIridioPropulsor.setText(String.valueOf(inventario.getPropulsor().getPrecio_del_arma().get("iridio")));
        this.precioPaladioPropulsor.setText(String.valueOf(inventario.getPropulsor().getPrecio_del_arma().get("paladio")));
        this.precioPlatinoPropulsor.setText(String.valueOf(inventario.getPropulsor().getPrecio_del_arma().get("platino")));
        this.precioZeroPropulsor.setText(String.valueOf(inventario.getPropulsor().getPrecio_del_arma().get("zero")));
    
        this.precioIridioEnergetica.setText(String.valueOf(inventario.getArmaEnergeticaLuz().getPrecio_del_arma().get("iridio")));
        this.precioPaladioEnergetica.setText(String.valueOf(inventario.getArmaEnergeticaLuz().getPrecio_del_arma().get("paladio")));
        this.precioPlatinoEnergetica.setText(String.valueOf(inventario.getArmaEnergeticaLuz().getPrecio_del_arma().get("platino")));
        this.precioZeroEnergetica.setText(String.valueOf(inventario.getArmaEnergeticaLuz().getPrecio_del_arma().get("zero")));
    
        this.precioIridioReactor.setText(String.valueOf(inventario.getReactor().getPrecio_del_arma().get("iridio")));
        this.precioPaladioReactor.setText(String.valueOf(inventario.getReactor().getPrecio_del_arma().get("paladio")));
        this.precioPlatinoReactor.setText(String.valueOf(inventario.getReactor().getPrecio_del_arma().get("platino")));
        this.precioZeroReactor.setText(String.valueOf(inventario.getReactor().getPrecio_del_arma().get("zero")));
    
        this.precioIridioHielo.setText(String.valueOf(inventario.getArmaHielo().getPrecio_del_arma().get("iridio")));
        this.precioPaladioHielo.setText(String.valueOf(inventario.getArmaHielo().getPrecio_del_arma().get("paladio")));
        this.precioPlatinoHielo.setText(String.valueOf(inventario.getArmaHielo().getPrecio_del_arma().get("platino")));
        this.precioZeroHielo.setText(String.valueOf(inventario.getArmaHielo().getPrecio_del_arma().get("zero")));
    
        this.precioIridioInvisibilidad.setText(String.valueOf(inventario.getInvisibilidad().getPrecio_del_arma().get("iridio")));
        this.precioPaladioInvisibilidad.setText(String.valueOf(inventario.getInvisibilidad().getPrecio_del_arma().get("paladio")));
        this.precioPlatinoInvisibilidad.setText(String.valueOf(inventario.getInvisibilidad().getPrecio_del_arma().get("platino")));
        this.precioZeroInvisibilidad.setText(String.valueOf(inventario.getInvisibilidad().getPrecio_del_arma().get("zero")));
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ComprarArma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ComprarArma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ComprarArma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ComprarArma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ComprarArma dialog = new ComprarArma(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonComprarArma;
    private javax.swing.JComboBox<String> comboBoxArmasComprar;
    private javax.swing.JLabel imagenBlindaje;
    private javax.swing.JLabel imagenEnergetica;
    private javax.swing.JLabel imagenHielo;
    private javax.swing.JLabel imagenInvisibilidad;
    private javax.swing.JLabel imagenMultinucleo;
    private javax.swing.JLabel imagenPropulsor;
    private javax.swing.JLabel imagenReactor;
    private javax.swing.JLabel imagenThanix;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel precioIridioBlindaje;
    private javax.swing.JLabel precioIridioEnergetica;
    private javax.swing.JLabel precioIridioHielo;
    private javax.swing.JLabel precioIridioInvisibilidad;
    private javax.swing.JLabel precioIridioMultinucleo;
    private javax.swing.JLabel precioIridioPropulsor;
    private javax.swing.JLabel precioIridioReactor;
    private javax.swing.JLabel precioIridioThanix;
    private javax.swing.JLabel precioPaladioBlindaje;
    private javax.swing.JLabel precioPaladioEnergetica;
    private javax.swing.JLabel precioPaladioHielo;
    private javax.swing.JLabel precioPaladioInvisibilidad;
    private javax.swing.JLabel precioPaladioMultinucleo;
    private javax.swing.JLabel precioPaladioPropulsor;
    private javax.swing.JLabel precioPaladioReactor;
    private javax.swing.JLabel precioPaladioThanix;
    private javax.swing.JLabel precioPlatinoBlindaje;
    private javax.swing.JLabel precioPlatinoEnergetica;
    private javax.swing.JLabel precioPlatinoHielo;
    private javax.swing.JLabel precioPlatinoInvisibilidad;
    private javax.swing.JLabel precioPlatinoMultinucleo;
    private javax.swing.JLabel precioPlatinoPropulsor;
    private javax.swing.JLabel precioPlatinoReactor;
    private javax.swing.JLabel precioPlatinoThanix;
    private javax.swing.JLabel precioZeroBlindaje;
    private javax.swing.JLabel precioZeroEnergetica;
    private javax.swing.JLabel precioZeroHielo;
    private javax.swing.JLabel precioZeroInvisibilidad;
    private javax.swing.JLabel precioZeroMultinucleo;
    private javax.swing.JLabel precioZeroPropulsor;
    private javax.swing.JLabel precioZeroReactor;
    private javax.swing.JLabel precioZeroThanix;
    // End of variables declaration//GEN-END:variables
}
