/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nave_espacial.vista;

import java.util.HashMap;
import java.util.LinkedList;
import java.util.List;
import javax.swing.JOptionPane;
import nave_espacial.controlador.ControladorDeCarga;
import nave_espacial.modelo.Gasolinera;
import nave_espacial.modelo.Planeta;
import nave_espacial.modelo.SistemaPlanetario;

/**
 *
 * @author Mafe
 */
public class CrearGasolinera extends javax.swing.JDialog {

    Gasolinera gasolinera;
    List<SistemaPlanetario> listaDeSistemasPlanetaRios;

    /**
     * Creates new form crearGasolinera
     */
    public CrearGasolinera(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        listaDeSistemasPlanetaRios = new LinkedList<>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        BotonCrearGasolinera = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        IridioSonda = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        PaladioSonda = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        PlatinoSonda = new javax.swing.JTextField();
        IridioGasolina = new javax.swing.JTextField();
        ZeroSonda = new javax.swing.JTextField();
        PaladioGasolina = new javax.swing.JTextField();
        PlatinoGasolina = new javax.swing.JTextField();
        ZeroGasolina = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        listaSPlanetarios = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        listaPlanetas = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Crear Gasolinera");

        BotonCrearGasolinera.setText("CREAR");
        BotonCrearGasolinera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCrearGasolineraActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel5.setText("Paladio");

        jLabel6.setText("Platino");

        jLabel7.setText("Zero");

        IridioGasolina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IridioGasolinaActionPerformed(evt);
            }
        });

        PaladioGasolina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PaladioGasolinaActionPerformed(evt);
            }
        });

        jLabel8.setText("Iridio");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Precio Gasolina:");

        jLabel9.setText("Paladio");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Precio Sonda:");

        jLabel10.setText("Platino");

        jLabel4.setText("Iridio");

        jLabel11.setText("Zero");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(IridioSonda, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(PaladioSonda, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(105, 105, 105)
                        .addComponent(ZeroSonda))
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(IridioGasolina, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(46, 46, 46))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(PaladioGasolina, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(47, 47, 47)
                                .addComponent(jLabel7))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(PlatinoGasolina, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10)
                                    .addComponent(PlatinoSonda, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(ZeroGasolina, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IridioGasolina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PaladioGasolina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PlatinoGasolina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ZeroGasolina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addGap(3, 3, 3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IridioSonda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PaladioSonda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PlatinoSonda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ZeroSonda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setText("Sistema planetario:");

        listaSPlanetarios.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        listaSPlanetarios.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                listaSPlanetariosItemStateChanged(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setText("Planeta:");

        listaPlanetas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(listaSPlanetarios, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(listaPlanetas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(listaSPlanetarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(listaPlanetas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(BotonCrearGasolinera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(96, 96, 96))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BotonCrearGasolinera)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IridioGasolinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IridioGasolinaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IridioGasolinaActionPerformed

    private void PaladioGasolinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PaladioGasolinaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PaladioGasolinaActionPerformed

    private void BotonCrearGasolineraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCrearGasolineraActionPerformed
        if (!listaSPlanetarios.getSelectedItem().toString().equals("") && !listaPlanetas.getSelectedItem().toString().equals("")) {
            validarDatos();
            //PRECIO GASOLINA
            HashMap<String, Integer> precioGasolina = new HashMap<>();
            precioGasolina.put("iridio", Integer.parseInt(IridioGasolina.getText()));
            precioGasolina.put("paladio", Integer.parseInt(PaladioGasolina.getText()));
            precioGasolina.put("platino", Integer.parseInt(PlatinoGasolina.getText()));
            precioGasolina.put("zero", Integer.parseInt(ZeroGasolina.getText()));

            //PRECIO SONDA
            HashMap<String, Integer> precioSonda = new HashMap<>();
            precioSonda.put("iridio", Integer.parseInt(IridioSonda.getText()));
            precioSonda.put("paladio", Integer.parseInt(PaladioSonda.getText()));
            precioSonda.put("platino", Integer.parseInt(PlatinoSonda.getText()));
            precioSonda.put("zero", Integer.parseInt(ZeroSonda.getText()));

            this.gasolinera.setPrecioGasolina(precioGasolina);
            this.gasolinera.setPrecioSonda(precioSonda);
            mandarGasolineraPlaneta();
            new ControladorDeCarga().guardarCambiosArchivos();
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Debe elegir un Sistema planetario y un planeta para crear la gasolinera");
        }
    }//GEN-LAST:event_BotonCrearGasolineraActionPerformed

    private void listaSPlanetariosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_listaSPlanetariosItemStateChanged
        if (!evt.getItemSelectable().toString().equals("")) {
            int indiceSplanetario = this.listaSPlanetarios.getSelectedIndex()-1;
            if (indiceSplanetario >= 0) {
                SistemaPlanetario splanetario = listaDeSistemasPlanetaRios.get(indiceSplanetario);
                cargarListaPlanetas(splanetario.getLista_planetas());
            }
        }
    }//GEN-LAST:event_listaSPlanetariosItemStateChanged

    private void cargarListaPlanetas(LinkedList<Planeta> listaPlaneta) {

        String listaNombres[] = new String[listaPlaneta.size() + 1];
        listaNombres[0] = "";
        for (int i = 0; i < listaPlaneta.size(); i++) {
            listaNombres[i + 1] = listaPlaneta.get(i).getNombre();
        }
        this.listaPlanetas.setModel(new javax.swing.DefaultComboBoxModel<>(listaNombres));
    }

    public void cargarListaSistemasPlanetarios() {

        String listaNombres[] = new String[this.listaDeSistemasPlanetaRios.size() + 1];
        listaNombres[0] = "";
        for (int i = 0; i < this.listaDeSistemasPlanetaRios.size(); i++) {
            listaNombres[i + 1] = this.listaDeSistemasPlanetaRios.get(i).getNombre();
        }
        this.listaSPlanetarios.setModel(new javax.swing.DefaultComboBoxModel<>(listaNombres));
    }

    private void validarDatos() {
        IridioGasolina.setText((IridioGasolina.getText().equals("")) ? "0" : IridioGasolina.getText());
        PaladioGasolina.setText((PaladioGasolina.getText().equals("")) ? "0" : PaladioGasolina.getText());
        PlatinoGasolina.setText((PlatinoGasolina.getText().equals("")) ? "0" : PlatinoGasolina.getText());
        ZeroGasolina.setText((ZeroGasolina.getText().equals("")) ? "0" : ZeroGasolina.getText());

        IridioSonda.setText((IridioSonda.getText().equals("")) ? "0" : IridioSonda.getText());
        PaladioSonda.setText((PaladioSonda.getText().equals("")) ? "0" : PaladioSonda.getText());
        PlatinoSonda.setText((PlatinoSonda.getText().equals("")) ? "0" : PlatinoSonda.getText());
        ZeroSonda.setText((ZeroSonda.getText().equals("")) ? "0" : ZeroSonda.getText());
    }

    private void mandarGasolineraPlaneta() {
        for (SistemaPlanetario sPlanetario : this.listaDeSistemasPlanetaRios) {
            if (sPlanetario.getNombre().equalsIgnoreCase(listaSPlanetarios.getSelectedItem().toString())) {
                for (Planeta planeta : sPlanetario.getLista_planetas()) {
                    if (planeta.getNombre().equalsIgnoreCase(listaPlanetas.getSelectedItem().toString())) {
                        planeta.setGasolinera_del_sistema(gasolinera);
                        return;
                    }
                }
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearGasolinera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearGasolinera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearGasolinera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearGasolinera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CrearGasolinera dialog = new CrearGasolinera(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonCrearGasolinera;
    private javax.swing.JTextField IridioGasolina;
    private javax.swing.JTextField IridioSonda;
    private javax.swing.JTextField PaladioGasolina;
    private javax.swing.JTextField PaladioSonda;
    private javax.swing.JTextField PlatinoGasolina;
    private javax.swing.JTextField PlatinoSonda;
    private javax.swing.JTextField ZeroGasolina;
    private javax.swing.JTextField ZeroSonda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JComboBox<String> listaPlanetas;
    private javax.swing.JComboBox<String> listaSPlanetarios;
    // End of variables declaration//GEN-END:variables

}
