/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nave_espacial.vista;

import java.util.List;
import nave_espacial.controlador.ControladorDeCarga;
import nave_espacial.modelo.Planeta;
import nave_espacial.modelo.SistemaPlanetario;
import nave_espacial.modelo.TeleTransportador;

/**
 *
 * @author Lenovo
 */
public class CrearTeletransportador extends javax.swing.JDialog {

    TeleTransportador teletransportador = new TeleTransportador();
    List<SistemaPlanetario> listaDeSistemasPlanetaRios;

    /**
     * Creates new form CrearTeletransportador
     */
    public CrearTeletransportador(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        comboBoxSP_Rele.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{}));
        comboBoxPlanetaRele.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{}));

    }

    private void mandarTeletransportadorAplaneta() {
        for (SistemaPlanetario sp : this.listaDeSistemasPlanetaRios) {
            if (sp.getNombre().equalsIgnoreCase(this.comboBoxSP_Rele.getSelectedItem().toString())) {
                for (Planeta planeta : sp.getLista_planetas()) {
                    if (planeta.getNombre().equalsIgnoreCase(this.comboBoxPlanetaRele.getSelectedItem().toString())) {
                        planeta.crearTeletransportador();
                        return;
                    }
                }
            }
        }
        //validan el nombre del sistema planetario
        //validan el nombre del planeta
        // planeta.crearTeletransportador();
    }

    public void cargarListaSistemasPlanetarios() {

        String listaNombres[] = new String[this.listaDeSistemasPlanetaRios.size() + 1];
        listaNombres[0] = "";
        for (int i = 0; i < this.listaDeSistemasPlanetaRios.size(); i++) {
            listaNombres[i + 1] = this.listaDeSistemasPlanetaRios.get(i).getNombre();
        }
        this.comboBoxSP_Rele.setModel(new javax.swing.DefaultComboBoxModel<>(listaNombres));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        crearRele = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        comboBoxSP_Rele = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        comboBoxPlanetaRele = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Crear Teletransportador");

        crearRele.setText("Crear");
        crearRele.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearReleActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setText("Elegir sistema planetario:");

        comboBoxSP_Rele.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboBoxSP_Rele.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboBoxSP_ReleItemStateChanged(evt);
            }
        });

        jLabel3.setText("Elegir planeta:");

        comboBoxPlanetaRele.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comboBoxSP_Rele, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(0, 66, Short.MAX_VALUE))
                    .addComponent(comboBoxPlanetaRele, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboBoxSP_Rele, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboBoxPlanetaRele, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(crearRele, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(crearRele)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboBoxSP_ReleItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboBoxSP_ReleItemStateChanged
        if (!this.comboBoxSP_Rele.getSelectedItem().toString().equalsIgnoreCase("")) {
            for (SistemaPlanetario sPlanetario : this.listaDeSistemasPlanetaRios) {
                if (sPlanetario.getNombre().equalsIgnoreCase(this.comboBoxSP_Rele.getSelectedItem().toString())) {
                    String nombrePlanetas[] = new String[sPlanetario.getLista_planetas().size()];
                    for (int i = 0; i < sPlanetario.getLista_planetas().size(); i++) {
                        nombrePlanetas[i] = sPlanetario.getLista_planetas().get(i).getNombre();
                    }
                    comboBoxPlanetaRele.setModel(new javax.swing.DefaultComboBoxModel<>(nombrePlanetas));
                }
            }
        }
    }//GEN-LAST:event_comboBoxSP_ReleItemStateChanged

    private void crearReleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearReleActionPerformed
        mandarTeletransportadorAplaneta();
        new ControladorDeCarga().guardarCambiosArchivos();
        this.dispose();
    }//GEN-LAST:event_crearReleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearTeletransportador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearTeletransportador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearTeletransportador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearTeletransportador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CrearTeletransportador dialog = new CrearTeletransportador(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboBoxPlanetaRele;
    private javax.swing.JComboBox<String> comboBoxSP_Rele;
    private javax.swing.JButton crearRele;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
