/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nave_espacial.vista;

import java.util.List;
import java.util.Random;
import nave_espacial.controlador.ControladorNebulosa;
import nave_espacial.modelo.Enemigo;
import nave_espacial.modelo.Planeta;
import nave_espacial.modelo.SistemaPlanetario;

/**
 *
 * @author Mafe
 */
public class CrearEnemigos extends javax.swing.JDialog {
    Enemigo enemigo=new Enemigo();
    List<SistemaPlanetario> listaDeSistemasPlanetaRios;
    /**
     * Creates new form CrearEnemigos
     */
    public CrearEnemigos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
        
       public void cargarListaSistemasPlanetarios() {
        String listaNombres[] = new String[this.listaDeSistemasPlanetaRios.size() + 1];
        listaNombres[0] = "";
        for (int i = 0; i < this.listaDeSistemasPlanetaRios.size(); i++) {
            listaNombres[i + 1] = this.listaDeSistemasPlanetaRios.get(i).getNombre();
        }
        this.ComboBoxEnemigosSP.setModel(new javax.swing.DefaultComboBoxModel<>(listaNombres));
    }
    
    private void mandarEnemigoAplaneta(){
        for (SistemaPlanetario sp:this.listaDeSistemasPlanetaRios){
         if (sp.getNombre().equalsIgnoreCase(this.ComboBoxEnemigosSP.getSelectedItem().toString())){
             for (Planeta planeta:sp.getLista_planetas()){
             if (planeta.getNombre().equalsIgnoreCase(this.ComboBoxEnemigoPlaneta.getSelectedItem().toString())){
                 for (int i = 0; i < Integer.parseInt(CantidadNodriza.getText()); i++) {
                     planeta.crearEnemigo(new Enemigo(planeta.getEnemigos().size(),new Random().nextInt(800-137)+137 , new Random().nextInt(400), "Nave nodriza", "alto")); 
                 }
                 for (int i = 0; i < Integer.parseInt(CantidadAvanzada.getText()); i++) {
                     planeta.crearEnemigo(new Enemigo(planeta.getEnemigos().size(),new Random().nextInt(800-137)+137 , new Random().nextInt(400), "Nave avanzada", "medio")); 
                 }
                 for (int i = 0; i < Integer.parseInt(CantidadExploradas.getText()); i++) {
                     planeta.crearEnemigo(new Enemigo(planeta.getEnemigos().size(),new Random().nextInt(800-137)+137 , new Random().nextInt(400), "Nave explorada", "bajo")); 
                 }
             }
             }
         }
            }
        
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        CantidadNodriza = new javax.swing.JTextField();
        CantidadAvanzada = new javax.swing.JTextField();
        CantidadExploradas = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        CrearEnemigos = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        ComboBoxEnemigosSP = new javax.swing.JComboBox<>();
        ComboBoxEnemigoPlaneta = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Crear Enemigos ");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Nave Nodriza (alta): ");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Nave Avanzada (medio):");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Naves Exploradas (baja):");

        CantidadNodriza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CantidadNodrizaActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("CANTIDAD");

        CrearEnemigos.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        CrearEnemigos.setText("CREAR");
        CrearEnemigos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearEnemigosActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("TIPO ENEMIGO");

        ComboBoxEnemigosSP.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ComboBoxEnemigosSPItemStateChanged(evt);
            }
        });

        ComboBoxEnemigoPlaneta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxEnemigoPlanetaActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Sistema Planetario");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Planeta");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6))
                        .addGap(72, 72, 72)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(CantidadNodriza)
                                .addComponent(CantidadAvanzada)
                                .addComponent(CantidadExploradas, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(CrearEnemigos))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(75, 75, 75)
                                .addComponent(ComboBoxEnemigosSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(jLabel7)))
                        .addGap(64, 64, 64)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(ComboBoxEnemigoPlaneta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(CantidadNodriza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(CantidadAvanzada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(CantidadExploradas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ComboBoxEnemigosSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ComboBoxEnemigoPlaneta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                        .addComponent(CrearEnemigos))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CantidadNodrizaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CantidadNodrizaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CantidadNodrizaActionPerformed

    private void CrearEnemigosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearEnemigosActionPerformed
       mandarEnemigoAplaneta();
       this.dispose();
    }//GEN-LAST:event_CrearEnemigosActionPerformed

    private void ComboBoxEnemigosSPItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ComboBoxEnemigosSPItemStateChanged
        if (!this.ComboBoxEnemigosSP.getSelectedItem().toString().equalsIgnoreCase("")) {
            for (SistemaPlanetario sPlanetario : this.listaDeSistemasPlanetaRios) {
                if (sPlanetario.getNombre().equalsIgnoreCase(this.ComboBoxEnemigosSP.getSelectedItem().toString())) {
                    String nombrePlanetas[] = new String[sPlanetario.getLista_planetas().size()];
                    for (int i = 0; i < sPlanetario.getLista_planetas().size(); i++) {
                        nombrePlanetas[i] = sPlanetario.getLista_planetas().get(i).getNombre();
                    }
                    ComboBoxEnemigoPlaneta.setModel(new javax.swing.DefaultComboBoxModel<>(nombrePlanetas));
                }
            }
        }
    }//GEN-LAST:event_ComboBoxEnemigosSPItemStateChanged

    private void ComboBoxEnemigoPlanetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxEnemigoPlanetaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBoxEnemigoPlanetaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearEnemigos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearEnemigos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearEnemigos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearEnemigos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CrearEnemigos dialog = new CrearEnemigos(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CantidadAvanzada;
    private javax.swing.JTextField CantidadExploradas;
    private javax.swing.JTextField CantidadNodriza;
    private javax.swing.JComboBox<String> ComboBoxEnemigoPlaneta;
    private javax.swing.JComboBox<String> ComboBoxEnemigosSP;
    private javax.swing.JButton CrearEnemigos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
