/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nave_espacial.vista;

import nave_espacial.controlador.ControladorPlaneta;
import static nave_espacial.controlador.ControladorInicio.nave;
/**
 *
 * @author Lenovo
 */
public class FramePlanetaJugar extends javax.swing.JFrame {
 private ControladorPlaneta  planetaControl;
    /**
     * Creates new form FramePlanetaJugar
     */
    public FramePlanetaJugar() {
        initComponents();
        this.setResizable(false);
    }
    
    
    public void definirFrame(ControladorPlaneta controlador){
        this.planetaControl = controlador;
        parametrizarFrame();
        this.setVisible(true);
    }
    
    private void parametrizarFrame(){
        this.setSize(900, 506);
        this.setLocationRelativeTo(null);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPlaneta1 = new nave_espacial.vista.PanelPlaneta();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        panelPlaneta1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelPlaneta1MousePressed(evt);
            }
        });

        javax.swing.GroupLayout panelPlaneta1Layout = new javax.swing.GroupLayout(panelPlaneta1);
        panelPlaneta1.setLayout(panelPlaneta1Layout);
        panelPlaneta1Layout.setHorizontalGroup(
            panelPlaneta1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        panelPlaneta1Layout.setVerticalGroup(
            panelPlaneta1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPlaneta1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPlaneta1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        System.out.println("tecla "+ evt);
        if(evt.getKeyCode()==10){
         nave.iniciarHilo();
        }
    }//GEN-LAST:event_formKeyPressed

    private void panelPlaneta1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelPlaneta1MousePressed
        if ((evt.getButton() == 1)) {
            if ((this.planetaControl.validarColisionMouseGasolinera(evt.getPoint()))) {
                ComprarGasolinaYsonda dialog = new ComprarGasolinaYsonda(new javax.swing.JFrame(), true);
                dialog.mostrarPrecios(this.planetaControl.getPlaneta().getGasolinera_del_sistema());
                dialog.setVisible(true);
            }
        }
        nave.moverNave(evt.getPoint());
    }//GEN-LAST:event_panelPlaneta1MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FramePlanetaJugar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FramePlanetaJugar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FramePlanetaJugar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FramePlanetaJugar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FramePlanetaJugar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private nave_espacial.vista.PanelPlaneta panelPlaneta1;
    // End of variables declaration//GEN-END:variables
  /**
     * @return the panelPlaneta1
     */
    public nave_espacial.vista.PanelPlaneta getPanelPlaneta() {
        return panelPlaneta1;
    }

}
