/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nave_espacial.vista;

import javax.swing.JOptionPane;
import nave_espacial.controlador.*;
import nave_espacial.modelo.Nebulosa;

/**
 *
 * @author Lenovo
 */
public class FrameViaLactea extends javax.swing.JFrame {

    private final ControladorViaLactea viaLacteaControl;

    /**
     * Creates new form FrameViaLactea
     */
    public FrameViaLactea() {
        initComponents();
        this.viaLacteaControl = new ControladorViaLactea(this);
        parametrizarFrame();
    }

    private void parametrizarFrame() {
        this.setSize(900, 506);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelViaLactea1 = new nave_espacial.vista.PanelViaLactea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelViaLactea1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panelViaLactea1MouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                panelViaLactea1MouseMoved(evt);
            }
        });
        panelViaLactea1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelViaLactea1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelViaLactea1Layout = new javax.swing.GroupLayout(panelViaLactea1);
        panelViaLactea1.setLayout(panelViaLactea1Layout);
        panelViaLactea1Layout.setHorizontalGroup(
            panelViaLactea1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 798, Short.MAX_VALUE)
        );
        panelViaLactea1Layout.setVerticalGroup(
            panelViaLactea1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 496, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelViaLactea1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelViaLactea1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void panelViaLactea1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelViaLactea1MouseClicked

        if ((evt.getButton() == 1)) {
            Nebulosa nebulosaClic;
            if ((nebulosaClic = viaLacteaControl.reconocerNebulosa(evt.getPoint()))== null) {
                String nombreNebulosa = JOptionPane.showInputDialog("Nombre nueva Nebulosa:");
                if (nombreNebulosa != null && !nombreNebulosa.equals("")) {
                    Nebulosa nueva = new Nebulosa(nombreNebulosa, evt.getX(), evt.getY());
                    viaLacteaControl.agregarNebulosa(nueva);
                }
            } else if(evt.getClickCount() == 2) {
                viaLacteaControl.crearNebulosa(nebulosaClic);
                this.dispose();
            }
        } else {

        }
    }//GEN-LAST:event_panelViaLactea1MouseClicked

    private void panelViaLactea1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelViaLactea1MouseMoved
    }//GEN-LAST:event_panelViaLactea1MouseMoved

    private void panelViaLactea1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelViaLactea1MouseDragged
        if(evt.getButton() == 0){
            viaLacteaControl.cambiarPosicionNebulosa(evt.getPoint());
        }

    }//GEN-LAST:event_panelViaLactea1MouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameViaLactea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameViaLactea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameViaLactea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameViaLactea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameViaLactea().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private nave_espacial.vista.PanelViaLactea panelViaLactea1;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the panelViaLactea1
     */
    public nave_espacial.vista.PanelViaLactea getPanelViaLactea() {
        return panelViaLactea1;
    }
}
