/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nave_espacial.vista;

import nave_espacial.controlador.*;

/**
 *
 * @author Lenovo
 */
public class FramePlaneta extends javax.swing.JFrame {

    private ControladorPlaneta planetaControl;
    private boolean atras;

    /**
     * Creates new form FramePlaneta
     */
    public FramePlaneta() {
        initComponents();
    }

    public void definirFrame(ControladorPlaneta controlador) {
        this.planetaControl = controlador;
        parametrizarFrame();
        this.setVisible(true);
    }

    private void parametrizarFrame() {
        this.setSize(900, 506);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPlaneta1 = new nave_espacial.vista.PanelPlaneta();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelPlaneta1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                panelPlaneta1MouseMoved(evt);
            }
        });
        panelPlaneta1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelPlaneta1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelPlaneta1Layout = new javax.swing.GroupLayout(panelPlaneta1);
        panelPlaneta1.setLayout(panelPlaneta1Layout);
        panelPlaneta1Layout.setHorizontalGroup(
            panelPlaneta1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 901, Short.MAX_VALUE)
        );
        panelPlaneta1Layout.setVerticalGroup(
            panelPlaneta1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 505, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelPlaneta1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelPlaneta1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void panelPlaneta1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelPlaneta1MouseMoved
        if (evt.getX() <= 80 && (evt.getY() >= 253 && evt.getY() < 300)) {
            this.panelPlaneta1.setAtras(true);
            atras = true;
        } else {
            this.panelPlaneta1.setAtras(false);
            atras = false;
        }
    }//GEN-LAST:event_panelPlaneta1MouseMoved

    private void panelPlaneta1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelPlaneta1MouseClicked
        if (atras) {
            this.planetaControl.regresar();
            this.dispose();
        }
    }//GEN-LAST:event_panelPlaneta1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FramePlaneta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FramePlaneta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FramePlaneta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FramePlaneta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FramePlaneta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private nave_espacial.vista.PanelPlaneta panelPlaneta1;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the panelPlaneta1
     */
    public nave_espacial.vista.PanelPlaneta getPanelPlaneta() {
        return panelPlaneta1;
    }

}
