/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nave_espacial.vista;

import nave_espacial.controlador.ControladorDeCarga;
import nave_espacial.controlador.ControladorNebulosa;
import nave_espacial.modelo.SistemaPlanetario;

/**
 * @author Lenovo
 */
public class FrameNebulosa extends javax.swing.JFrame {

    private ControladorNebulosa nebulosaControl;
    private boolean crearRuta;
    private boolean atras;

    /**
     * Creates new form FrameNebulosa
     */
    public FrameNebulosa() {
        initComponents();
    }

    public void definirFrame(ControladorNebulosa controlador) {
        this.nebulosaControl = controlador;
        parametrizarFrame();
        this.setVisible(true);
        this.toFront();
        this.requestFocus();
    }

    private void parametrizarFrame() {
        this.setSize(900, 506);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelNebulosa2 = new nave_espacial.vista.PanelNebulosa();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                formKeyReleased(evt);
            }
        });

        panelNebulosa2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panelNebulosa2MouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                panelNebulosa2MouseMoved(evt);
            }
        });
        panelNebulosa2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelNebulosa2MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelNebulosa2MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                panelNebulosa2MouseReleased(evt);
            }
        });
        panelNebulosa2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                panelNebulosa2KeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelNebulosa2, javax.swing.GroupLayout.DEFAULT_SIZE, 876, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelNebulosa2, javax.swing.GroupLayout.DEFAULT_SIZE, 457, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void panelNebulosa2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelNebulosa2MouseClicked
        if ((evt.getButton() == 1) && (!this.crearRuta)) {
            if (!atras) {
                SistemaPlanetario sPlanetario;
                if ((sPlanetario = nebulosaControl.reconocerSistemaPlanetario(evt.getPoint())) == null) {
                    SistemaPlanetario sistemaplanetario = new SistemaPlanetario();
                    CrearSistemaPlanetario dialog = new CrearSistemaPlanetario(new javax.swing.JFrame(), true);
                    dialog.sistemaPlanetario = sistemaplanetario;
                    dialog.setVisible(true);
                    if (!sistemaplanetario.getNombre().equals("")) {
                        sistemaplanetario.setPosX(evt.getX());
                        sistemaplanetario.setPosY(evt.getY());
                        nebulosaControl.agregarSistemaPlanetario(sistemaplanetario);
                    }
                } else {
                    if (evt.getClickCount() == 2) {
                        nebulosaControl.crearSistemaPlanetario(sPlanetario);
                        this.dispose();
                    }
                }
            } else {
                nebulosaControl.regresar();
                this.dispose();
            }
        } else {

        }
    }//GEN-LAST:event_panelNebulosa2MouseClicked

    private void panelNebulosa2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelNebulosa2MouseDragged
        if (evt.getButton() == 0) {
            if (!crearRuta) {
                nebulosaControl.cambiarPosicionSistemaPlanetario(evt.getPoint());
            } else {
                this.nebulosaControl.lineaTransicion[2] = evt.getX();
                this.nebulosaControl.lineaTransicion[3] = evt.getY();
                this.panelNebulosa2.setLineaTransicion(this.nebulosaControl.lineaTransicion);
            }
        }
    }//GEN-LAST:event_panelNebulosa2MouseDragged

    private void panelNebulosa1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelNebulosa1MouseDragged
    }//GEN-LAST:event_panelNebulosa1MouseDragged

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        switch (evt.getKeyCode()) {
            case 17:
                this.crearRuta = true;
                break;
            case 82:
                EliminarRuta dialog = new EliminarRuta(new javax.swing.JFrame(), true);
                dialog.definirParametro(this.nebulosaControl.getNebulosa());
                dialog.setVisible(true);
                new ControladorDeCarga().guardarCambiosArchivos();
                break;
            default:
                System.out.println("key evt:" + evt.getKeyCode());
        }
        
    }//GEN-LAST:event_formKeyPressed

    private void formKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyReleased
        
        switch (evt.getKeyCode()) {
            case 17:
                this.crearRuta = false;
                break;
            default:
                System.out.println("key evt:" + evt.getKeyCode());
        }
        
    }//GEN-LAST:event_formKeyReleased

    private void panelNebulosa2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelNebulosa2MousePressed
        if ((evt.getButton() == 1)) {
            if (crearRuta) {
                this.nebulosaControl.lineaTransicion[0] = evt.getX();
                this.nebulosaControl.lineaTransicion[1] = evt.getY();
                this.nebulosaControl.lineaTransicion[2] = evt.getX();
                this.nebulosaControl.lineaTransicion[3] = evt.getY();
                this.panelNebulosa2.setLineaTransicion(this.nebulosaControl.lineaTransicion);
            }
        }
    }//GEN-LAST:event_panelNebulosa2MousePressed

    private void panelNebulosa2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelNebulosa2MouseReleased
        if (evt.getButton() == 1) {
            if (crearRuta) {
                crearRuta = !crearRuta;
                this.nebulosaControl.evaluarTransicion();
                this.panelNebulosa2.setLineaTransicion(this.nebulosaControl.lineaTransicion);
            }
        }
    }//GEN-LAST:event_panelNebulosa2MouseReleased

    private void panelNebulosa2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_panelNebulosa2KeyPressed
    }//GEN-LAST:event_panelNebulosa2KeyPressed

    private void panelNebulosa2MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelNebulosa2MouseMoved
        if (evt.getX() <= 80 && (evt.getY() >= 253 && evt.getY() < 300)) {
            this.panelNebulosa2.setAtras(true);
            atras = true;
        } else {
            this.panelNebulosa2.setAtras(false);
            atras = false;
        }
    }//GEN-LAST:event_panelNebulosa2MouseMoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameNebulosa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameNebulosa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameNebulosa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameNebulosa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameNebulosa().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private nave_espacial.vista.PanelNebulosa panelNebulosa2;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the panelNebulosa1
     */
    public nave_espacial.vista.PanelNebulosa getPanelNebulosa() {
        return panelNebulosa2;
    }
}
