/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nave_espacial.vista;

import nave_espacial.controlador.ControladorDeCarga;
import nave_espacial.controlador.ControladorSistemaPlanetario;
import nave_espacial.modelo.Planeta;

/**
 *
 * @author Lenovo
 */
public class FrameSistemaPlanetario extends javax.swing.JFrame {

    private ControladorSistemaPlanetario sistemaPlanetarioControl;
    private boolean crearRuta;
    private boolean atras;

    /**
     * Creates new form FrameSistemaPlanetario
     */
    public FrameSistemaPlanetario() {
        initComponents();
    }

    public void definirFrame(ControladorSistemaPlanetario controlador) {
        sistemaPlanetarioControl = controlador;
        parametrizarFrame();
        this.setVisible(true);
    }

    private void parametrizarFrame() {
        this.setSize(900, 506);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelSistemaPlanetario1 = new nave_espacial.vista.PanelSistemaPlanetario();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                formKeyReleased(evt);
            }
        });

        panelSistemaPlanetario1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panelSistemaPlanetario1MouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                panelSistemaPlanetario1MouseMoved(evt);
            }
        });
        panelSistemaPlanetario1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelSistemaPlanetario1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelSistemaPlanetario1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                panelSistemaPlanetario1MouseReleased(evt);
            }
        });

        javax.swing.GroupLayout panelSistemaPlanetario1Layout = new javax.swing.GroupLayout(panelSistemaPlanetario1);
        panelSistemaPlanetario1.setLayout(panelSistemaPlanetario1Layout);
        panelSistemaPlanetario1Layout.setHorizontalGroup(
            panelSistemaPlanetario1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 895, Short.MAX_VALUE)
        );
        panelSistemaPlanetario1Layout.setVerticalGroup(
            panelSistemaPlanetario1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 468, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelSistemaPlanetario1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelSistemaPlanetario1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void panelSistemaPlanetario1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelSistemaPlanetario1MouseClicked
        if ((evt.getButton() == 1) && (!this.crearRuta)) {
            if (!atras) {
                Planeta planeta;
                if ((planeta = sistemaPlanetarioControl.reconocerPlaneta(evt.getPoint())) == null) {
                    planeta = new Planeta();
                    CrearPlaneta dialog = new CrearPlaneta(new javax.swing.JFrame(), true);
                    dialog.planeta = planeta;
                    dialog.setVisible(true);
                    if (planeta != null) {
                        planeta.setPosX(evt.getX());
                        planeta.setPosY(evt.getY());
                        sistemaPlanetarioControl.agregarPlaneta(planeta);
                    }
                } else {
                    if (evt.getClickCount() == 2) {
                        sistemaPlanetarioControl.crearPlaneta(planeta);
                        this.dispose();
                    }
                }
            } else {
                sistemaPlanetarioControl.regresar();
                this.dispose();
            }
        } else {

        }
    }//GEN-LAST:event_panelSistemaPlanetario1MouseClicked

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        switch (evt.getKeyCode()) {
            case 17:
                this.crearRuta = true;
                break;
            case 82:
                EliminarRuta dialog = new EliminarRuta(new javax.swing.JFrame(), true);
                dialog.definirParametro(this.sistemaPlanetarioControl.getsPlanetario());
                dialog.setVisible(true);
                new ControladorDeCarga().guardarCambiosArchivos();
                break;
            default:
                System.out.println("key evt:" + evt.getKeyCode());
        }
    }//GEN-LAST:event_formKeyPressed

    private void formKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyReleased
        switch (evt.getKeyCode()) {
            case 17:
                this.crearRuta = false;
                break;
            default:
                System.out.println("key evt:" + evt.getKeyCode());
        }
    }//GEN-LAST:event_formKeyReleased

    private void panelSistemaPlanetario1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelSistemaPlanetario1MouseDragged
        if (evt.getButton() == 0) {
            if (!crearRuta) {
                sistemaPlanetarioControl.cambiarPosicionPlaneta(evt.getPoint());
            } else {
                this.sistemaPlanetarioControl.lineaTransicion[2] = evt.getX();
                this.sistemaPlanetarioControl.lineaTransicion[3] = evt.getY();
                this.panelSistemaPlanetario1.setLineaTransicion(this.sistemaPlanetarioControl.lineaTransicion);
            }
        }
    }//GEN-LAST:event_panelSistemaPlanetario1MouseDragged

    private void panelSistemaPlanetario1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelSistemaPlanetario1MouseReleased
        if (evt.getButton() == 1) {
            this.sistemaPlanetarioControl.evaluarTransicion();
            this.panelSistemaPlanetario1.setLineaTransicion(this.sistemaPlanetarioControl.lineaTransicion);
        }
    }//GEN-LAST:event_panelSistemaPlanetario1MouseReleased

    private void panelSistemaPlanetario1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelSistemaPlanetario1MousePressed
        if ((evt.getButton() == 1)) {
            if (crearRuta) {
                this.sistemaPlanetarioControl.lineaTransicion[0] = evt.getX();
                this.sistemaPlanetarioControl.lineaTransicion[1] = evt.getY();
                this.sistemaPlanetarioControl.lineaTransicion[2] = evt.getX();
                this.sistemaPlanetarioControl.lineaTransicion[3] = evt.getY();
                this.panelSistemaPlanetario1.setLineaTransicion(this.sistemaPlanetarioControl.lineaTransicion);
            }
        }
    }//GEN-LAST:event_panelSistemaPlanetario1MousePressed

    private void panelSistemaPlanetario1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelSistemaPlanetario1MouseMoved
        if (evt.getX() <= 80 && (evt.getY() >= 253 && evt.getY() < 300)) {
            this.panelSistemaPlanetario1.setAtras(true);
            atras = true;
        } else {
            this.panelSistemaPlanetario1.setAtras(false);
            atras = false;
        }
    }//GEN-LAST:event_panelSistemaPlanetario1MouseMoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameSistemaPlanetario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameSistemaPlanetario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameSistemaPlanetario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameSistemaPlanetario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameSistemaPlanetario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private nave_espacial.vista.PanelSistemaPlanetario panelSistemaPlanetario1;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the panelSistemaPlanetario1
     */
    public nave_espacial.vista.PanelSistemaPlanetario getPanelSistemaPlanetario() {
        return panelSistemaPlanetario1;
    }

}
