/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nave_espacial.vista;

import java.awt.Graphics;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import nave_espacial.controlador.ControladorPlaneta;
import nave_espacial.modelo.Algoritmos;
import nave_espacial.modelo.Nave;
import nave_espacial.modelo.Planeta;
import static nave_espacial.controlador.ControladorInicio.nave;
/**
 *
 * @author Lenovo
 */
public class PanelInicio extends javax.swing.JPanel {

    private ImageIcon fondo;
    public FrameInicio frameinicio;

    /**
     * Creates new form PanelInicio
     */
    public PanelInicio() {
        initComponents();
        cargarImagenes();
    }

    private void cargarImagenes() {
        fondo = new ImageIcon(getClass().getResource("imagenes/inicio/inicio.jpg"));
    }

    @Override
    public void paintComponent(Graphics g) {
        pintarFondo(g);
        try {
            Thread.sleep(150);
        } catch (InterruptedException ex) {
            Logger.getLogger(PanelViaLactea.class.getName()).log(Level.SEVERE, null, ex);
        }
        repaint();
    }

    private void pintarFondo(Graphics g) {
        g.drawImage(fondo.getImage(), 0, 0, 900, 506, this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jButton1.setText("Editar Espacio");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Jugar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(76, 76, 76))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(68, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new FrameViaLactea().setVisible(true);
        this.frameinicio.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        nave = new Nave();
        JOptionPane.showMessageDialog(null, "Presione Enter para iniciar!!");
        this.frameinicio.dispose();
        //this.frameinicio.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    // End of variables declaration//GEN-END:variables
}
