/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nave_espacial.vista;

import java.awt.Color;
import java.awt.Graphics;
import java.util.LinkedList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import nave_espacial.modelo.Nebulosa;
import static nave_espacial.controlador.ControladorInicio.nave;

/**
 *
 * @author Lenovo
 */
public class PanelViaLactea extends javax.swing.JPanel {

    private ImageIcon imagenNebulosa;
    private List<ImageIcon> imagenesFondo;
    private int indiceImagen;
    private List<Nebulosa> listaNebulosa;

    /**
     * Creates new form PanelViaLactea
     */
    public PanelViaLactea() {
        initComponents();
        cargarImagenes();

    }

    private void cargarImagenes() {
        indiceImagen = 0;
        imagenesFondo = new LinkedList<>();
        imagenNebulosa = new ImageIcon(getClass().getResource("imagenes/viaLactea/estrella.png"));
        for (int i = 0; i < 357; i++) {
            ImageIcon imagen = new ImageIcon(getClass().getResource("imagenes/viaLactea/Snapshot_" + i + ".png"));
            imagenesFondo.add(imagen);
        }
    }

    @Override
    public void paintComponent(Graphics g) {
        pintarFondo(g);
        pintaNebulosas(g);
        pintarnave(g);
        try {
            Thread.sleep(100);
        } catch (InterruptedException ex) {
            Logger.getLogger(PanelViaLactea.class.getName()).log(Level.SEVERE, null, ex);
        }
        repaint();
    }

    private void pintarnave(Graphics g) {
        if (nave != null) {
            g.drawImage(nave.getImagen().getImage(), nave.getX(), nave.getY(), 100, 46, this);
        }
    }

    private void pintarFondo(Graphics g) {
        if (indiceImagen < 357) {
            g.drawImage(imagenesFondo.get(indiceImagen).getImage(), 0, 0, 900, 506, this);
            indiceImagen++;
        } else {
            indiceImagen = 0;
        }

    }

    private void pintaNebulosas(Graphics g) {
        if (listaNebulosa != null) {
            for (Nebulosa nebulosa : listaNebulosa) {
                g.setColor(Color.white);
                g.drawImage(imagenNebulosa.getImage(), nebulosa.getPosX() - 50, nebulosa.getPosY() - 50,100,100, this);
                g.drawString(nebulosa.getNombre(), nebulosa.getPosX(), nebulosa.getPosY());

            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 767, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 401, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param listaNebulosa the listaNebulosa to set
     */
    public void setListaNebulosa(List<Nebulosa> listaNebulosa) {
        this.listaNebulosa = listaNebulosa;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
